# Generated by Django 3.1.12 on 2025-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Reg_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=50)),
                ('Program', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
