# Generated by Django 3.1.12 on 2025-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_auto_20250414_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
