# Generated by Django 3.1.12 on 2025-04-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_auto_20250416_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=10000)),
                ('Category', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
