# Generated by Django 5.2 on 2025-04-17 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('Comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='Board.event')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='Board.student')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Board.event')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.student')),
            ],
            options={
                'unique_together': {('Id', 'Username')},
            },
        ),
    ]
