# Generated by Django 5.2 on 2025-04-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0005_comments_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Id',
            new_name='EventId',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Id',
            new_name='EventId',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Id',
            new_name='EventId',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('EventId', 'Username')},
        ),
    ]
