# Generated by Django 5.2 on 2025-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0006_rename_id_comments_eventid_rename_id_event_eventid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.CharField(default='student@mubas.ac.mw', max_length=100),
        ),
    ]
