# Generated by Django 5.2 on 2025-04-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0007_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='EventId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Program',
        ),
        migrations.AlterField(
            model_name='student',
            name='Reg_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comments',
            name='Noticeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='Board.notice'),
        ),
        migrations.AddField(
            model_name='like',
            name='Likeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Board.notice'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('Likeid', 'Username')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='EventId',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
